name: mobile
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  shared_preferences: ^2.0.18
  remixicon: ^1.0.0
  url_launcher: ^6.1.10
  share_plus: ^6.3.1
  transparent_image: ^2.0.1
  vector_math: ^2.1.4
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/icon.png'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600

    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
  uses-material-design: true
  assets:
    - assets/ca/
    - assets/images/
